// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTB5OSVVqQMn5h9jWUgDmhZZwY52j2rM8',
    appId: '1:537290147276:android:43b45c80daa9fdc5eb0969',
    messagingSenderId: '537290147276',
    projectId: 'sample-dd045',
    databaseURL: 'https://sample-dd045-default-rtdb.firebaseio.com',
    storageBucket: 'sample-dd045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABkamf0ftbmdQU0Q_xICI4EgNiuoQrqVo',
    appId: '1:537290147276:ios:32fed25770292bf0eb0969',
    messagingSenderId: '537290147276',
    projectId: 'sample-dd045',
    databaseURL: 'https://sample-dd045-default-rtdb.firebaseio.com',
    storageBucket: 'sample-dd045.appspot.com',
    iosClientId: '537290147276-an25ui297mas407n930k31hd2j290or3.apps.googleusercontent.com',
    iosBundleId: 'com.example.madEx3',
  );
}
